Update publish-java-maven.yml

diff --git a/.github/workflows/publish-java-maven.yml b/.github/workflows/publish-java-maven.yml
--- a/.github/workflows/publish-java-maven.yml
+++ b/.github/workflows/publish-java-maven.yml
@@ -43,5 +43,10 @@ jobs:
 
       - name: Upload WAR to Release
         run: |
-          war_file="${{ steps.find_and_check_war.outputs.war_file }}"
-          gh release upload java-maven5-1.1 "$war_file" --clobber
+         war_file="$GITHUB_WORKSPACE/target/java-maven5-1.1.war"
+         if [ ! -f "$war_file" ]; then
+         echo "ERROR: WAR file not found."
+         exit 1
+         fi
+         gh release upload java-maven5-1.1 "$war_file" --clobber
+
