Update publish-java-maven.yml

diff --git a/.github/workflows/publish-java-maven.yml b/.github/workflows/publish-java-maven.yml
--- a/.github/workflows/publish-java-maven.yml
+++ b/.github/workflows/publish-java-maven.yml
@@ -34,14 +34,14 @@ jobs:
       - name: Find and check WAR file
         id: find_and_check_war
         run: |
-         war_file=$(ls $GITHUB_WORKSPACE/target/*.war 2>/dev/null | head -n 1)
-         if [ -z "$war_file" ]; then
-         echo "ERROR: WAR file not found."
-         exit 1
-         else
-         echo "::set-output name=war_file::$war_file"
-         fi
-
+          shopt -s nullglob
+          war_files=( $GITHUB_WORKSPACE/target/*.war )
+          if [ ${#war_files[@]} -eq 0 ]; then
+            echo "ERROR: No WAR files found."
+            exit 1
+          else
+            echo "::set-output name=war_file::${war_files[0]}"
+          fi
 
       - name: Authenticate with GitHub CLI
         run: gh auth login --with-token <<<"${{ secrets.GH_TOKEN }}"
@@ -52,5 +52,5 @@ jobs:
 
       - name: Upload WAR to Release
         run: |
-          war_file="${{ steps.find_war.outputs.war_file }}"
+          war_file="${{ steps.find_and_check_war.outputs.war_file }}"
           gh release upload java-maven5-1.1 "$war_file" --clobber
