Update publish-java-maven.yml

diff --git a/.github/workflows/publish-java-maven.yml b/.github/workflows/publish-java-maven.yml
--- a/.github/workflows/publish-java-maven.yml
+++ b/.github/workflows/publish-java-maven.yml
@@ -31,15 +31,17 @@ jobs:
       - name: List files in target directory
         run: ls -l $GITHUB_WORKSPACE/target
 
-      - name: Find WAR file
-        id: find_war
+      - name: Find and check WAR file
+        id: find_and_check_war
         run: |
-          war_file=$(ls $GITHUB_WORKSPACE/target/*.war | grep -v '\.original$' | head -n 1)
-          if [ -z "$war_file" ]; then
-            echo "ERROR: WAR file not found."
-            exit 1
-          fi
-          echo "::set-output name=war_file::$war_file"
+         war_file=$(ls $GITHUB_WORKSPACE/target/*.war 2>/dev/null | head -n 1)
+         if [ -z "$war_file" ]; then
+         echo "ERROR: WAR file not found."
+         exit 1
+         else
+         echo "::set-output name=war_file::$war_file"
+         fi
+
 
       - name: Authenticate with GitHub CLI
         run: gh auth login --with-token <<<"${{ secrets.GH_TOKEN }}"
